{
    "type": "bundle",
    "id": "bundle--b2419376-a280-48dd-911e-92d9e6bc2b6e",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "type": "relationship",
            "id": "relationship--a5b41632-a553-4abe-aa68-9ce6898e642d",
            "description": "(Citation: Symantec WastedLocker June 2020)",
            "target_ref": "tool--ff6caf67-ea1f-4895-b80e-4bb0fc31c6db",
            "modified": "2021-10-13T22:50:48.900Z",
            "source_ref": "intrusion-set--01e28736-2ffc-455b-9880-ed4d1407ae07",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "relationship_type": "uses",
            "created": "2021-10-13T22:50:48.900Z",
            "external_references": [
                {
                    "url": "https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/wastedlocker-ransomware-us",
                    "description": "Symantec Threat Intelligence. (2020, June 25). WastedLocker: Symantec Identifies Wave of Attacks Against U.S. Organizations. Retrieved May 20, 2021.",
                    "source_name": "Symantec WastedLocker June 2020"
                }
            ]
        }
    ]
}